version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: agrimalipostgres
    ports:
      - '6500:5432'
    volumes:
      - agrimalidb:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    container_name: agrimaliredis
    ports:
      - '6379:6379'
    volumes:
      - redisdb:/data
volumes:
  agrimalidb:
  redisdb:
